[2023-05-13 16:19:17] [INFO] [test_allure_attach_log.py]/[line: 10]/[test_case1] 用例1的 info 级别的日志 
[2023-05-13 16:19:17] [WARNING] [test_allure_attach_log.py]/[line: 12]/[test_case1] 用例1的 warning 级别的日志 
[2023-05-13 16:19:17] [ERROR] [test_allure_attach_log.py]/[line: 13]/[test_case1] 用例1的 error 级别的日志 
[2023-05-13 16:19:17] [CRITICAL] [test_allure_attach_log.py]/[line: 14]/[test_case1] 用例1的  fatal 级别的日志 
[2023-05-13 16:25:04] [ERROR] [test_allure_attach_log.py]/[line: 29]/[test_case1] This is TestEpic's 4th case 
[2023-05-13 16:25:28] [INFO] [test_allure_attach_log.py]/[line: 11]/[test_case1] This is TestEpic's first case 
[2023-05-13 16:25:28] [WARNING] [test_allure_attach_log.py]/[line: 23]/[test_case3] This is TestEpic's third case 
[2023-05-13 16:25:28] [ERROR] [test_allure_attach_log.py]/[line: 29]/[test_case4] This is TestEpic's 4th case 
[2023-05-13 16:29:47] [INFO] [test_allure_attach_log.py]/[line: 11]/[test_case1] This is TestEpic's first case 
[2023-05-13 16:29:47] [DEBUG] [test_allure_attach_log.py]/[line: 17]/[test_case2] This is TestEpic's second case 
[2023-05-13 16:29:47] [WARNING] [test_allure_attach_log.py]/[line: 23]/[test_case3] This is TestEpic's third case 
[2023-05-13 16:29:47] [ERROR] [test_allure_attach_log.py]/[line: 29]/[test_case4] This is TestEpic's 4th case 
[2023-05-13 16:30:30] [INFO] [test_allure_attach_log.py]/[line: 11]/[test_case1] This is TestEpic's first case 
[2023-05-13 16:30:30] [DEBUG] [test_allure_attach_log.py]/[line: 17]/[test_case2] This is TestEpic's second case 
[2023-05-13 16:30:30] [WARNING] [test_allure_attach_log.py]/[line: 23]/[test_case3] This is TestEpic's third case 
[2023-05-13 16:30:30] [ERROR] [test_allure_attach_log.py]/[line: 29]/[test_case4] This is TestEpic's 4th case 
[2023-05-13 16:34:06] [INFO] [test_allure_attach_log.py]/[line: 11]/[test_case1] This is TestEpic's first case 
[2023-05-13 16:34:06] [DEBUG] [test_allure_attach_log.py]/[line: 17]/[test_case2] This is TestEpic's second case 
[2023-05-13 16:34:06] [WARNING] [test_allure_attach_log.py]/[line: 23]/[test_case3] This is TestEpic's third case 
[2023-05-13 16:34:06] [ERROR] [test_allure_attach_log.py]/[line: 29]/[test_case4] This is TestEpic's 4th case 
